#!/usr/bin/env node
// Fetches monster Markdown from vitusventure/5thSRD and generates src/data/srdEnemies.ts.
// Usage: npm run srd:sync
// Add monster slugs (= filename without .md) to scripts/monster-list.json to expand the roster.

'use strict';

const https = require('https');
const fs = require('fs');
const path = require('path');
const { parseMonster } = require('./parseSrdMonster');

const RAW_BASE =
  'https://raw.githubusercontent.com/vitusventure/5thSRD/master/docs/gamemaster_rules/monsters';

const OUT_PATH = path.join(__dirname, '../src/data/srdEnemies.ts');
const LIST_PATH = path.join(__dirname, 'monster-list.json');

function fetchText(url) {
  return new Promise((resolve, reject) => {
    https
      .get(url, (res) => {
        if (res.statusCode === 404) {
          reject(new Error(`404 Not Found`));
          return;
        }
        if (res.statusCode !== 200) {
          reject(new Error(`HTTP ${res.statusCode}`));
          return;
        }
        let data = '';
        res.on('data', (chunk) => (data += chunk));
        res.on('end', () => resolve(data));
      })
      .on('error', reject);
  });
}

function serializeMonster(m) {
  const indent = (s, n) =>
    s
      .split('\n')
      .map((l, i) => (i === 0 ? l : ' '.repeat(n) + l))
      .join('\n');

  const attacksStr = m.attacks
    .map(
      (a) =>
        `      {\n` +
        `        name: ${JSON.stringify(a.name)},\n` +
        `        attackBonus: ${a.attackBonus},\n` +
        `        damageDice: ${JSON.stringify(a.damageDice)},\n` +
        `        damageType: ${JSON.stringify(a.damageType)},\n` +
        `        range: ${JSON.stringify(a.range)},\n` +
        `      }`
    )
    .join(',\n');

  const scoresStr = Object.entries(m.abilityScores)
    .map(([k, v]) => `      ${k}: ${v}`)
    .join(',\n');

  return (
    `  ${m.id}: {\n` +
    `    id: ${JSON.stringify(m.id)},\n` +
    `    name: ${JSON.stringify(m.name)},\n` +
    `    cr: ${m.cr},\n` +
    `    ac: ${m.ac},\n` +
    `    maxHP: ${m.maxHP},\n` +
    `    speed: ${m.speed},\n` +
    `    abilityScores: {\n${scoresStr},\n    },\n` +
    `    initiativeBonus: ${m.initiativeBonus},\n` +
    `    attacks: [\n${attacksStr},\n    ],\n` +
    `    multiattackCount: ${m.multiattackCount},\n` +
    `    xp: ${m.xp},\n` +
    `    flavor: ${JSON.stringify(m.flavor)},\n` +
    `    iconHint: ${JSON.stringify(m.iconHint)},\n` +
    `  }`
  );
}

async function main() {
  const { monsters: slugs } = JSON.parse(fs.readFileSync(LIST_PATH, 'utf8'));
  console.log(`Fetching ${slugs.length} monsters from vitusventure/5thSRD…\n`);

  const parsed = [];
  const failures = [];

  for (const slug of slugs) {
    const url = `${RAW_BASE}/${slug}.md`;
    try {
      const markdown = await fetchText(url);
      const monster = parseMonster(slug, markdown);
      if (monster) {
        parsed.push(monster);
        console.log(`  ✓  ${monster.name} (CR ${monster.cr})`);
      } else {
        failures.push({ slug, reason: 'parse failed — missing ability scores or attacks' });
        console.warn(`  ✗  ${slug}: parse failed`);
      }
    } catch (err) {
      failures.push({ slug, reason: err.message });
      console.warn(`  ✗  ${slug}: ${err.message}`);
    }
  }

  const entries = parsed.map(serializeMonster).join(',\n');

  const output =
    `// AUTO-GENERATED by scripts/srd-sync.js — do not edit manually.\n` +
    `// Source: https://github.com/vitusventure/5thSRD (CC-BY-4.0)\n` +
    `// Run \`npm run srd:sync\` to regenerate from the SRD repository.\n` +
    `import type { EnemyStatBlock } from 'src/data/enemies';\n\n` +
    `export const SRD_ENEMIES: Record<string, EnemyStatBlock> = {\n` +
    `${entries}\n` +
    `};\n`;

  fs.writeFileSync(OUT_PATH, output, 'utf8');

  console.log(`\n✅  ${parsed.length} monsters written → src/data/srdEnemies.ts`);
  if (failures.length) {
    console.log(`⚠️   ${failures.length} failures:`);
    for (const f of failures) console.log(`     ${f.slug}: ${f.reason}`);
  }
}

main().catch((err) => {
  console.error('Fatal:', err.message);
  process.exit(1);
});
